language: java

# use Java 12
jdk:
  - openjdk12

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
    - $HOME/.gradle

# configuration to deploy our application to HEROKU
deploy:
  provider: heroku
  api_key:
    secure: baa8892d-74c6-4856-85e3-1e20e3c7a713
  app: continuous-delivery-heroku
  on:
    repo: jadsonjs/continuous-delivery